version: "3"

services: 
    web:
        container_name: api-database
        restart: always
        build: .
        ports:
            - "80:8080"
        links:
            - mongo
        volumes: 
            - api.py:/usr/src/app    
        volumes: 
            - /proc/:/elements/procs/        
    mongo:
        container_name: mongo-database
        restart: always
        image: mongo
        ports: 
            - "90:27017"
        volumes: 
            - /mongodb:/data/db    




